---
- name: Install git
  apt: pkg=git state=installed
  sudo: yes

- name: Copy git configuration
  template: src=gitconfig dest=/home/{{ username }}/.gitconfig

- name: Copy git ssh config
  template: src=sshconfig dest=/home/{{ username }}/.ssh/config
