---
- name: Install git
  apt: pkg=git state=installed
  sudo: yes

- name: Copy git configuration
  template: src=gitconfig dest=/home/{{ username }}/.gitconfig

- name: Copy git ssh config
  template: src=sshconfig dest=/home/{{ username }}/.ssh/config

- name: Install connect
  apt: pkg=connect-proxy state=installed
  sudo: yes

- name: Copy socks5proxywrapper
  copy:
    src=socks5proxywrapper
    dest=/usr/bin/socks5proxywrapper
    owner=root
    group=root
    mode=0775
  sudo: yes
