---
- name: Install ansible
  pip: name=ansible state=present
  sudo: yes

- name: mkdir ansible hosts
  file:
    state=directory
    dest=/etc/ansible
    owner={{ username }}
    group={{ username }}
    mode=0775
  sudo: yes

- name: Copy ansible configuration
  copy:
    src=hosts
    dest=/etc/ansible/hosts
    owner={{ username }}
    group={{ username }}
    mode=0664
  sudo: yes
