---
- name: Install deps
  apt: pkg={{ item }} state=installed
  with_items:
    - supervisor
    - python-m2crypto
    - python-gevent
  sudo: yes

- name: Install shadowsocks
  pip: name={{ item }} state=present
  with_items:
    - shadowsocks
    - superlance
  sudo: yes

- name: Mkdir shadowsocks config dir
  file:
    state=directory
    dest=/etc/shadowsocks
    owner={{ username }}
    group={{ username }}
    mode=0775
  sudo: yes

- name: Copy shadowsocks config file
  copy:
    src=config.json
    dest=/etc/shadowsocks/config.json

- name: Copy sslocal supervisor config file
  template: src=sslocal.conf dest=/etc/supervisor/conf.d/sslocal.conf
  sudo: yes
