---
- name: Copy sources.list
  template: src=sources.list dest=/etc/apt/sources.list
  notify: apt update
  sudo: yes

- name: Install common tools
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-file
    - unzip
    - git
    - zsh
    - mercurial
    - vim
    - tmux
    - tree
    - cscope
    - ctags
  sudo: yes
