---
- name: Copy sources.list
  template: src=sources.list dest=/etc/apt/sources.list
  sudo: yes

- name: apt update
  apt: update_cache=yes
  sudo: yes

- name: Install common tools
  apt: pkg={{ item }} state=installed
  with_items:
    - apt-file
    - unzip
    - git
    - zsh
    - mercurial
    - vim
    - tmux
    - tree
    - cscope
  sudo: yes
