---
- name: Install php and deps
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-enchant
    - php5-fpm
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-json
    - php5-mongo
    - php5-mysql
    - php5-pgsql
    - php5-sqlite
    - php5-xhprof
    - php-pear

#- name: Disable default pool
  #command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  #notify: restart php-fpm

#- name: Copy php-fpm configuration
  #template: src=www.conf dest=/etc/php-fpm.d/
  #notify: restart php-fpm
