---
- name: Install mcrypt
  apt: pkg=mcrypt state=installed
  sudo: yes

- name: Install php and deps
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-enchant
    - php5-fpm
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-json
    - php5-mongo
    - php5-mysql
    - php5-pgsql
    - php5-sqlite
    - php5-xhprof
    - php5-mcrypt
    - php-pear
    - libpcre3-dev
  sudo: yes

- name: copy *.ini
  copy:
    src={{ item }}.ini
    dest=/etc/php5/mods-available/{{ item }}.ini
    owner=root
    group=root
    mode=0664
  with_items:
    - mcrypt
  sudo: yes

- name: link *.ini
  file: state=link dest=/etc/php5/{{ item[0] }}/conf.d/20-{{ item[1] }}.ini src=../../mods-available/{{ item[1] }}.ini
  with_nested:
    - { 'cli', 'fpm' }
    - { 'mongo', 'xhprof', 'mcrypt' }
  sudo: yes
