---
- name: Install php and deps
  apt: pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-curl
    - php5-dev
    - php5-enchant
    - php5-fpm
    - php5-gd
    - php5-geoip
    - php5-gmp
    - php5-imagick
    - php5-json
    - php5-mongo
    - php5-mysql
    - php5-pgsql
    - php5-sqlite
    - php5-xhprof
    - php-pear

- include: composer.yml
