---
- name: Install vim
  apt: pkg=vim state=installed

- name: Vim configuration
  shell: wget https://raw.github.com/thbourlove/vim/master/install -O - | sh creates={{ home_dir }}/.vimrc
  sudo: no
