---
- name: Install ruby
  apt: pkg=ruby state=installed

- name: Install ruby-dev
  apt: pkg=ruby-dev state=installed

- name: Copy config files
  copy:
    src=gemrc
    dest=/home/{{ username }}/.gemrc
