---
- name: Install ruby
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby
    - ruby-dev
  sudo: yes

- name: Copy config files
  copy:
    src=gemrc
    dest=/home/{{ username }}/.gemrc
